version: '3.8'

services: 
  postgress:
    image: postgress:15
    container_name: postgress_db
    environment:
      POSTGRES_USER: lamadev
      POSTGRES_PASSWORD: lama123456
      POSTGRES_DB: school
    ports: 
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: "postgresql://lamadev:lama123456@localhost:5432/school"
    depends_on:
      - postgres 